// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaTarefas.Context;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(SistemaDbContext))]
    [Migration("20230616225323_02")]
    partial class _02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("en_US.utf8")
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaTarefas.Entities.Projeto", b =>
                {
                    b.Property<int>("idproject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idproject");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idproject"));

                    b.Property<string>("nomeProjeto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("nomecliente")
                        .HasColumnType("text")
                        .HasColumnName("nomecliente");

                    b.Property<decimal?>("precohora")
                        .HasColumnType("numeric")
                        .HasColumnName("precohora");

                    b.HasKey("idproject");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("SistemaTarefas.Entities.Tarefa", b =>
                {
                    b.Property<int>("id_tarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tarefa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_tarefa"));

                    b.Property<string>("descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("hora_fim")
                        .HasColumnType("date")
                        .HasColumnName("hora_fim");

                    b.Property<DateTime>("hora_inicio")
                        .HasColumnType("date")
                        .HasColumnName("hora_inicio");

                    b.Property<int?>("id_projeto")
                        .HasColumnType("integer")
                        .HasColumnName("id_projeto");

                    b.Property<int?>("id_utilizador")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizador");

                    b.Property<decimal?>("precohora")
                        .HasColumnType("numeric")
                        .HasColumnName("precohora");

                    b.HasKey("id_tarefa");

                    b.HasIndex("id_projeto");

                    b.HasIndex("id_utilizador");

                    b.ToTable("tarefas", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Entities.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idUser");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUser"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("nhoras")
                        .HasColumnType("integer")
                        .HasColumnName("nhoras");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.HasKey("idUser");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SistemaTarefas.Entities.Tarefa", b =>
                {
                    b.HasOne("SistemaTarefas.Entities.Projeto", "Projetos")
                        .WithMany("Tarefas")
                        .HasForeignKey("id_projeto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaTarefas.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("id_utilizador");

                    b.Navigation("Projetos");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SistemaTarefas.Entities.Projeto", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
